### ISSUE TITLE
unexpected KeyError: '__builtins__' during import in an evaluated native method call

### ISSUE THREAD

**Issue by vthriller** [PyO3/pyo3#1035]
```rust
use pyo3::prelude::*;
use pyo3::types::IntoPyDict;

#[pyclass]
pub struct Foo {}
#[pymethods]
impl Foo {
	fn method(&mut self, py: Python) {
		dbg!("successfully entered the method");
		let _sys = PyModule::import(py, "sys")
			.map_err(|e| {
				e.clone_ref(py).print(py);
				e
			})
			.unwrap();
	}
}

fn main() -> PyResult<()> {
	let gil = Python::acquire_gil();
	let py = gil.python();

	let foo = PyCell::new(py, Foo {})?;

	let method = (**foo).to_object(py)
		.getattr(py, "method")?
		.to_object(py);

	py.eval("method()", Some(
		[("method", method)].into_py_dict(py)
	), None)?;

	Ok(())
}
```

This is as far as I can minimize it: `method.call0(py)?` works flawlessly in place of `py.eval`.

```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 1.69s
     Running `target/debug/wtf`
[src/main.rs:9] "successfully entered the method" = "successfully entered the method"
KeyError: '__builtins__'
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: Py(0x7fd0bf798760, PhantomData) }', src/main.rs:10:20
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1268
  14: core::result::Result<T,E>::unwrap
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/result.rs:1005
  15: wtf::Foo::method
             at src/main.rs:10
  16: wtf::__init90297311022353647::__init90297311022353647::__wrap::{{closure}}
             at src/main.rs:6
  17: std::panicking::try::do_call
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:331
  18: __rust_try
  19: std::panicking::try
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:274
  20: std::panic::catch_unwind
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:394
  21: wtf::__init90297311022353647::__init90297311022353647::__wrap
             at src/main.rs:6
  22: _PyMethodDef_RawFastCallKeywords
             at Objects/call.c:694
  23: _PyCFunction_FastCallKeywords
             at Objects/call.c:734
  24: call_function
             at Python/ceval.c:4568
  25: _PyEval_EvalFrameDefault
             at Python/ceval.c:3124
  26: _PyEval_EvalCodeWithName
             at Python/ceval.c:3930
  27: PyEval_EvalCodeEx
             at Python/ceval.c:3959
  28: PyEval_EvalCode
             at Python/ceval.c:524
  29: run_mod
             at Python/pythonrun.c:1035
  30: PyRun_StringFlags
             at Python/pythonrun.c:959
  31: pyo3::python::Python::run_code
             at /home/thriller/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.11.1/src/python.rs:237
  32: pyo3::python::Python::eval
             at /home/thriller/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.11.1/src/python.rs:172
  33: wtf::main
             at src/main.rs:29
  34: std::rt::lang_start::{{closure}}
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/rt.rs:67
  35: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  36: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  37: std::panicking::try
             at src/libstd/panicking.rs:274
  38: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  39: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  40: std::rt::lang_start
             at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/rt.rs:67
  41: main
  42: __libc_start_main
  43: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
--- PyO3 is resuming a panic after fetching a PanicException from Python. ---
Python stack trace below:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PyErr { type: Py(0x7fd0bf798760, PhantomData) }
```

### Environment

- Your operating system and version:
  Gentoo Linux.
- Your python version:
  ```
  $ python --version
  Python 3.7.7
  ```
- How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?:
  `emerge`, no virtualenv.
- Your Rust version (`rustc --version`):
  ```
  $ rustc --version
  rustc 1.44.0 (49cae5576 2020-06-01)
  ```
- Your PyO3 version:
  ```
  $ grep -A1 '"pyo3"' Cargo.lock 
  name = "pyo3"
  version = "0.11.1"
  ```
- Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`:
  I did (cfa5b2e013466a36b9ae8822a196d2a7501c6ad3); KeyError is still present.

**Comment by vthriller** [comment]
…guess what? `PYTHON_SYS_EXECUTABLE=python3.8` (3.8.2) solved this.

I'm gonna keep this issue open though: it's so obscure in its nature I can't tell whether it's the problem with pyo3, (older versions of) Python, or actually both, so it's up to you to decide whether this needs any action on your part.

**Comment by davidhewitt** [comment]
Thanks for reporting!

From a bit of digging, it looks to me like `PyModule::import`'s underlying implementation (inside CPython, not PyO3) does attempt to access `__builtins__`. Presumably Python 3.7 behaved slightly differently somewhere deep in the internals compared to Python 3.8.

For now I think there's nothing we can change here on our part.
