### ISSUE TITLE
Embedded CPython 3.7b1 crashes on initialization

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [PyO3/pyo3#110]
To reproduce, run any test that uses Python interpreter:
```
pyo3> cargo test -- objects::list::test::test_get_item

running 1 test
test objects::list::test::test_get_item ... FAILED

failures:

---- objects::list::test::test_get_item stdout ----
        thread 'objects::list::test::test_get_item' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', src\pythonrun.rs:45:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:382
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:390
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:576
   6: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:537
   7: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:521
   8: pyo3::pythonrun::prepare_freethreaded_python::{{closure}}
             at .\src\pythonrun.rs:45
   9: std::sync::once::{{impl}}::call_once::{{closure}}<closure>
             at C:\projects\rust\src\libstd\sync\once.rs:227
  10: std::sync::once::Once::call_inner
             at C:\projects\rust\src\libstd\sync\once.rs:340
  11: std::sync::once::Once::call_once<closure>
             at C:\projects\rust\src\libstd\sync\once.rs:227
  12: pyo3::pythonrun::prepare_freethreaded_python
             at .\src\pythonrun.rs:38
  13: pyo3::pythonrun::GILGuard::acquire
             at .\src\pythonrun.rs:254
  14: pyo3::python::Python::acquire_gil
             at .\src\python.rs:106
  15: pyo3::objects::list::test::test_get_item
             at .\src\objects\list.rs:209
  16: test::run_test::{{closure}}
             at C:\projects\rust\src\libtest\lib.rs:1446
  17: core::ops::function::FnOnce::call_once
             at C:\projects\rust\src\libcore\ops\function.rs:223
  18: alloc::boxed::{{impl}}::call_box<(),closure>
             at C:\projects\rust\src\liballoc\boxed.rs:788
  19: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:102
  20: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:458
  21: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:358
  22: test::run_test::run_test_inner::{{closure}}
             at C:\projects\rust\src\libtest\lib.rs:1414


failures:
    objects::list::test::test_get_item

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 116 filtered out
```

Version info:
```
> python
Python 3.7.0b1 (v3.7.0b1:9561d7f, Jan 31 2018, 07:26:34) [MSC v.1900 64 bit (AMD64)] on win32

> rustc --version --verbose
rustc 1.25.0-nightly (29c8276ce 2018-02-07)
binary: rustc
commit-hash: 29c8276cee4a0eab7e0634ff25c6b47bd9f87c6c
commit-date: 2018-02-07
host: x86_64-pc-windows-msvc
release: 1.25.0-nightly
LLVM version: 4.0

pyo3> git log -1
commit 63a2066a39a6389f24ed1d5acda322425ade0937 (HEAD -> master, origin/master, origin/HEAD)
Author: Nikolay Kim <fafhrd91@gmail.com>
Date:   Fri Jan 19 10:27:37 2018 -0800

    can not use workspace for examples
```

**Comment by Vlad-Shcherbina** [comment]
[They say](https://docs.python.org/3/c-api/init.html#c.Py_Initialize) ` Py_Initialize()` should be called before using any other Python/C API (with the unspoken exception of `Py_IsInitialized()`, I assume). So I tried swapping the assertion and the initialization call in https://github.com/PyO3/pyo3/blob/8b7a57891bf959261716db169c7b0711bc03e1fc/src/pythonrun.rs#L44-L51

But it did not help.

I think this has something to do with the very recent change https://github.com/python/cpython/commit/2914bb32e2adf8dff77c0ca58b33201bc94e398c#diff-baf5eab51059d96fb8837152dab0d1a4R689 , where they began calling `PyEval_InitThreads()` inside `Py_Initialize()`.

**Comment by fafhrd91** [comment]
@Vlad-Shcherbina are you interested in pyo3 project? would you be interested to join project? seems you know what you are talking about :)
I don't have much time for this project at the moment.

**Comment by Vlad-Shcherbina** [comment]
I'm interested in the project. What do you mean by joining? Commit access and some maintenance responsibilities? Let's see how it goes.

For now I can say that I'm likely to fix the things that bother me.

**Comment by fafhrd91** [comment]
Yes, all of it. Commmit access, maintenance, feature development. But just in general, project is healthier if several developers knows how everything work and can continue development.

As a side note, seems specialization soundness get resolved, so we should be able to compile pyo3 on stable by the end of the year or even earlier.
