### ISSUE TITLE
Failing tests on master

### ISSUE THREAD

**Issue by Askaholic** [PyO3/pyo3#1213]
## 🐛 Bug Reports

After I cloned the repo for the first time I ran the tests to check for errors and I got two. I'm reporting them here by suggestion of @kngwyu .

```
failures:

---- buffer::test::test_array_buffer stdout ----
thread 'buffer::test::test_array_buffer' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: 0x55fb0678ffe0 }', src/buffer.rs:675:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- exceptions::test::test_check_exception stdout ----
thread 'exceptions::test::test_check_exception' panicked at 'Can not import module: socket: PyErr { type: 0x55fb0678ffe0 }', src/exceptions.rs:499:5


failures:
    buffer::test::test_array_buffer
    exceptions::test::test_check_exception
```

### 🌍 Environment

 - Your operating system and version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
$ uname -rsm       
Linux 5.4.0-39-generic x86_64
```
 - Your python version: 
```
$ python --version
Python 2.7.17
$ python3 --version
Python 3.8.3
```
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Python 2 - apt, Python 3 - Compiled from source, installed to system.
 - Your Rust version (`rustc --version`):
```
$ rustc --version
rustc 1.48.0-nightly (8876ffc92 2020-10-02)
```
 - Your PyO3 version: Master @ 37ce406ba18eb4f42bebf14c4bf33596f1f0dc3b
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: See above

### 💥 Reproducing

I ran:
```
$ cargo test
```

**Comment by kngwyu** [comment]
Thanks!
>  Python 3 - Compiled from source, installed to system.

Hmm ... :thinking: 
I encountered this error with pyenv but couldn't figure out the cause. 
I *think* some compile configuration or envvar matter, but am not sure.

**Comment by davidhewitt** [comment]
@Askaholic can you please run the output of the `print_info` example in https://github.com/davidhewitt/python-config ?

I have a theory that it's because you're linking statically, and that at link time the necessary symbols are being cut out. Not sure if we can easily fix this, but some confirmation would be great :)

**Comment by Askaholic** [comment]
Sure:

```
$ cargo run --example print_info
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/examples/print_info`
thread 'main' panicked at 'no entry found for key', /home/username/Documents/python-config/src/lib.rs:50:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

with backtrace:

```
$ RUST_BACKTRACE=1 cargo run --example print_info
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/examples/print_info`
thread 'main' panicked at 'no entry found for key', /home/username/Documents/python-config/src/lib.rs:50:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8876ffc9235dade728e1fbc4be4c85415fdd0bcd/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/8876ffc9235dade728e1fbc4be4c85415fdd0bcd/library/core/src/panicking.rs:85
   2: core::option::expect_failed
             at /rustc/8876ffc9235dade728e1fbc4be4c85415fdd0bcd/library/core/src/option.rs:1226
   3: core::option::Option<T>::expect
             at /rustc/8876ffc9235dade728e1fbc4be4c85415fdd0bcd/library/core/src/option.rs:346
   4: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at /rustc/8876ffc9235dade728e1fbc4be4c85415fdd0bcd/library/std/src/collections/hash/map.rs:1095
   5: python_config::get_config_from_interpreter
             at ./src/lib.rs:50
   6: python_config::find_interpreters::{{closure}}
             at ./src/lib.rs:149
   7: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/8876ffc9235dade728e1fbc4be4c85415fdd0bcd/library/core/src/ops/function.rs:269
   8: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::find_map
             at /rustc/8876ffc9235dade728e1fbc4be4c85415fdd0bcd/library/core/src/slice/iter/macros.rs:268
   9: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/8876ffc9235dade728e1fbc4be4c85415fdd0bcd/library/core/src/iter/adapters/mod.rs:1245
  10: print_info::find_interpreter
             at ./examples/print_info.rs:4
  11: print_info::main
             at ./examples/print_info.rs:14
  12: core::ops::function::FnOnce::call_once
             at /rustc/8876ffc9235dade728e1fbc4be4c85415fdd0bcd/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

And here is the output of the python code when executed with python3:
```
$ python3 print_info.py 
version_major 3
version_minor 8
implementation CPython
libdir /usr/local/lib
ld_version 3.8
base_prefix /usr/local
shared False
executable /usr/local/bin/python3
calcsize_pointer 8
```

And here it is with `python`:
```
$ python print_info.py 
('version_major', 2)
('version_minor', 7)
('implementation', 'CPython')
('libdir', '/usr/lib')
('ld_version', '2.7')
('base_prefix', '/usr')
('shared', True)
('executable', '/usr/bin/python')
('calcsize_pointer', 8)
```
You need to include `from __future__ import print_function` for it to produce the same output in python2.

P.S. import json` is unused :P

**Comment by Askaholic** [comment]
I guess I can recompile with 
```
--enable-shared         enable building a shared Python library (default is no)
```

**Comment by davidhewitt** [comment]
> I guess I can recompile with

yep, I think so! 

(Looks like I need to fixup that `print_info` example, thanks for debugging and running just the python snippet!)

**Comment by Askaholic** [comment]
I recompiled as a shared library:
```
$ python3 print_info.py
version_major 3
version_minor 8
implementation CPython
libdir /usr/local/lib
ld_version 3.8
base_prefix /usr/local
shared True
executable /usr/local/bin/python3
calcsize_pointer 8
```
But now cargo doesn't seem to be calling the linker correctly. I always get this error:
```
$ cargo test
   Compiling pyo3 v0.12.3 (/home/username/Documents/pyo3)
warning: attribute should be applied to a foreign function or static
  --> src/ffi/methodobject.rs:20:20
   |
20 |   #[cfg_attr(Py_3_8, link_name = "_PyObject_Vectorcall")]
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
21 | / pub type PyObject_Vectorcall = unsafe extern "C" fn(
22 | |     slf: *mut PyObject,
23 | |     // positional and keyword arguments
24 | |     args: *const *mut PyObject,
...  |
28 | |     kwnames: *mut PyObject,
29 | | ) -> *mut PyObject;
   | |___________________- not a foreign function or static
   |
   = note: `#[warn(unused_attributes)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!

warning: attribute should be applied to a foreign function or static
  --> src/ffi/methodobject.rs:32:20
   |
32 |   #[cfg_attr(Py_3_8, link_name = "PyVectorcall_Call")]
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
33 | / pub type PyVectorcall_Call = unsafe extern "C" fn(
34 | |     obj: *mut PyObject,
35 | |     tuple: *mut PyObject,
36 | |     dict: *mut PyObject,
37 | | ) -> *mut PyObject;
   | |___________________- not a foreign function or static
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!

warning: 2 warnings emitted

    Finished test [unoptimized + debuginfo] target(s) in 3.38s
     Running target/debug/deps/pyo3-0468062fb954ea2d
/home/username/Documents/pyo3/target/debug/deps/pyo3-0468062fb954ea2d: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
error: test failed, to rerun pass '--lib'
```
I'm not sure if the warnings are relevant, but I was already getting them when compiling with the statically linked version of Python. I can tell that libpython is not linked in correctly:
```
$ ldd target/debug/deps/pyo3-0468062fb954ea2d
        linux-vdso.so.1 (0x00007fff2ad36000)
        libpython3.8.so.1.0 => not found
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4c31803000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4c31412000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4c31e4c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4c31074000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4c30e55000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4c30c51000)
```
Even though the link search path seems to be set correctly in `build.rs`:
```
  --- stdout
  cargo:rustc-link-lib=python3.8
  cargo:rustc-link-search=native=/usr/local/lib
  cargo:rustc-cfg=Py_3_5
  cargo:rustc-cfg=Py_3_6
  cargo:rustc-cfg=Py_3_7
  cargo:rustc-cfg=Py_3_8
  cargo:rustc-cfg=Py_3
  cargo:rustc-cfg=py_sys_config="WITH_THREAD"
  cargo:python_flags=FLAG_WITH_THREAD=1,CFG_Py_3_5,CFG_Py_3_6,CFG_Py_3_7,CFG_Py_3_8
  cargo:rerun-if-env-changed=LIB
  cargo:rerun-if-env-changed=LD_LIBRARY_PATH
  cargo:rerun-if-env-changed=PYO3_PYTHON
  cargo:rerun-if-env-changed=PYTHON_SYS_EXECUTABLE
  cargo:rerun-if-env-changed=PATH
```
And the file exists there:
```
$ ls /usr/local/lib
libpython3.7m.a  libpython3.8.so      libpython3.9.a   libpython3.9.so.1.0  pkgconfig  python3.6  python3.8
libpython3.8.a   libpython3.8.so.1.0  libpython3.9.so  libpython3.so        python2.7  python3.7  python3.9
```
No idea what's causing that linking error.

**Comment by davidhewitt** [comment]
Interesting. Is `libpython3.8.so` a symlink to `libpython3.8.so.1.0`?

I don't think the warnings are relevant - they've been there for a little while; I just haven't got around to fixing them.

If you run with `cargo test --verbose`, does the output give any hints?

**Comment by Askaholic** [comment]
Not sure how useful it is, but it spits out a bunch of lines like this:
```
Running `rustc --crate-name test_pyself --edition=2018 tests/test_pyself.rs --error-format=json --json=diagnostic-rendered-ansi 
--emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --test --cfg 'feature="ctor"' --cfg 'feature="default"' 
--cfg 'feature="indoc"' --cfg 'feature="inventory"' --cfg 'feature="macros"' --cfg 'feature="paste"' --cfg 'feature="pyo3cls"' 
--cfg 'feature="unindent"' -C metadata=52dd71853fe11276 -C extra-filename=-52dd71853fe11276 
--out-dir /home/username/Documents/pyo3/target/debug/deps 
-C incremental=/home/username/Documents/pyo3/target/debug/incremental 
-L dependency=/home/username/Documents/pyo3/target/debug/deps 
--extern assert_approx_eq=/home/username/Documents/pyo3/target/debug/deps/libassert_approx_eq-34229977c19e1cf6.rlib 
--extern ctor=/home/username/Documents/pyo3/target/debug/deps/libctor-34dcf87c515cac4a.so 
--extern indoc=/home/username/Documents/pyo3/target/debug/deps/libindoc-5b797644d42839d2.rlib 
--extern inventory=/home/username/Documents/pyo3/target/debug/deps/libinventory-509e80f695994877.rlib 
--extern libc=/home/username/Documents/pyo3/target/debug/deps/liblibc-4ecf900a0c275dfb.rlib 
--extern parking_lot=/home/username/Documents/pyo3/target/debug/deps/libparking_lot-41b7534952790008.rlib 
--extern paste=/home/username/Documents/pyo3/target/debug/deps/libpaste-318f55209d8e7557.rlib 
--extern pyo3=/home/username/Documents/pyo3/target/debug/deps/libpyo3-3856580341f5d256.rlib 
--extern pyo3cls=/home/username/Documents/pyo3/target/debug/deps/libpyo3cls-fb06a56a5aa8ce3e.so 
--extern rustversion=/home/username/Documents/pyo3/target/debug/deps/librustversion-0b00f573c5de0807.so 
--extern trybuild=/home/username/Documents/pyo3/target/debug/deps/libtrybuild-731d8c2ef3b27c67.rlib 
--extern unindent=/home/username/Documents/pyo3/target/debug/deps/libunindent-2a0325e491dee639.rlib 
-L native=/usr/local/lib --cfg Py_3_5 --cfg Py_3_6 --cfg Py_3_7 --cfg Py_3_8 --cfg Py_3 --cfg 'py_sys_config="WITH_THREAD"'`
```
One possible thought: Not sure what the `--cfg Py_3_5 --cfg Py_3_6 --cfg Py_3_7 --cfg Py_3_8 --cfg Py_3` part is about, but I don't have python3.5 installed at all, and python3.6 was installed through apt so it lives in `/usr/lib` instead of `/usr/local/lib` like python3.7, 3.8 and 3.9.

libpython3.8.so is a symlink:
```
$ ll /usr/local/lib/libpython3.8.so
lrwxrwxrwx 1 root root 19 Oct  9 11:59 /usr/local/lib/libpython3.8.so -> libpython3.8.so.1.0
```

**Comment by Askaholic** [comment]
Ok, finally got it working with the shared version of python. After doing some reading on various random github issues, I found the suggestion of simply running `ldconfig` after the build. This seems to fix everything, you can see in the official docker file they do it as well: 

https://github.com/docker-library/python/blob/e7ee625fbac412e87e6e24423c7d5009cbbc394c/3.8/buster/slim/Dockerfile#L85

Now all the tests pass just fine!

**Comment by davidhewitt** [comment]
Good to know! I'm going to leave this issue open for now just to remind me to improve the static linking UX.
