### ISSUE TITLE
Segfault with std::regex::Regex

### ISSUE THREAD

**Issue by plattfot** [PyO3/pyo3#140]
Hi,
I'm having some issues with rust's regex library and python. As soon as I create a new regex it will segfault. I started out using rust-cpython as I'm brand new to rust and didn't want to start mixing in nightly. But couldn't get it to work, see this issue:  https://github.com/dgrunwald/rust-cpython/issues/130

So today I decided to try out pyo3 and see if I have any luck with that. But same thing. 

```toml
#Cargo.toml
[package]
name = "picmover"
version = "0.1.0"

[lib]
name = "picmover"
crate-type = ["dylib"]
plugin=true

[dependencies]
regex = "0.2"
pyo3 = "0.2"
```
```rust
//lib.rs
#![feature(proc_macro, specialization)]

extern crate pyo3;
extern crate regex;

use regex::Regex;

use pyo3::prelude::*;

#[py::modinit(libpicmover)]
fn init_mod(py: Python, m: &PyModule) -> PyResult<()> {
    #[pyfn(m, "segfault")]
    fn segfault_py(name: &str ) -> PyResult<String> {
        let re = Regex::new(r"segfault").unwrap();
        Ok(name.to_string())
    }
    Ok(())
}
```
At least this time I got a better backtrace
```sh
RUST_BACKTRACE=1 LD_LIBRARY_PATH=~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib PYTHONPATH=target/debug/ gdb python

(gdb) r
Starting program: /usr/bin/python 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from libpicmover import segfault
>>> segfault("")
thread '<unnamed>' panicked at 'index out of bounds: the len is 25 but the index is 140737301839888', /checkout/src/libcore/slice/mod.rs:871:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:347
   6: rust_begin_unwind
             at libstd/panicking.rs:323
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::panicking::panic_bounds_check
             at libcore/panicking.rs:58
   9: <usize as core::slice::SliceIndex<[T]>>::index_mut
             at /checkout/src/libcore/slice/mod.rs:871
  10: core::slice::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /checkout/src/libcore/slice/mod.rs:778
  11: <alloc::vec::Vec<T> as core::ops::index::IndexMut<I>>::index_mut
             at /checkout/src/liballoc/vec.rs:1716
  12: regex::compile::Compiler::fill
             at /home/plattfot/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.10/src/compile.rs:678
  13: regex::compile::Compiler::fill
             at /home/plattfot/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.10/src/compile.rs:682
  14: regex::compile::Compiler::c_repeat_zero_or_more
             at /home/plattfot/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.10/src/compile.rs:590
  15: regex::compile::Compiler::c_repeat
             at /home/plattfot/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.10/src/compile.rs:557
  16: regex::compile::Compiler::c
             at /home/plattfot/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.10/src/compile.rs:361
  17: regex::compile::Compiler::c_dotstar
             at /home/plattfot/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.10/src/compile.rs:390
  18: regex::compile::Compiler::compile_one
             at /home/plattfot/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.10/src/compile.rs:144
  19: regex::compile::Compiler::compile
             at /home/plattfot/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.10/src/compile.rs:129
  20: regex::exec::ExecBuilder::build
             at /home/plattfot/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.10/src/exec.rs:304
  21: regex::re_builder::unicode::RegexBuilder::build
             at /home/plattfot/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.10/src/re_builder.rs:77
  22: regex::re_unicode::Regex::new
             at /home/plattfot/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.10/src/re_unicode.rs:176
  23: picmover::init_mod::segfault_py
             at src/lib.rs:10
  24: picmover::init_mod::__wrap
             at src/lib.rs:10
  25: _PyCFunction_FastCallDict
  26: <unknown>
  27: _PyEval_EvalFrameDefault
  28: PyEval_EvalCodeEx
  29: PyEval_EvalCode
  30: <unknown>
  31: <unknown>
  32: PyRun_InteractiveLoopFlags
  33: <unknown>
  34: <unknown>
  35: main
  36: __libc_start_main
  37: _start
fatal runtime error: failed to initiate panic, error 5

Program received signal SIGABRT, Aborted.
0x00007ffff7837860 in raise () from /usr/lib/libc.so.6
```
Any idea why it's going out of bounds?

Thanks

**Comment by plattfot** [comment]
ssokolow discovered what was wrong in https://github.com/dgrunwald/rust-cpython/issues/130. I'd put dylib instead of cdylib, which was causing rust to segfault for some reason.
