### ISSUE TITLE
Potential bug: importing tensorflow in thread prevents the process from exiting

### ISSUE THREAD

**Issue by qwfy** [PyO3/pyo3#1448]
### 🌍 Environment

 - Your operating system and version: Arch Linux, kernel 5.10.17-1-lts
 - Your python version: 3.9.1
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Arch linux's package manager, pacman, no virtualenv or any other env
 - Your Rust version (`rustc --version`): rustc 1.47.0 (18bf6b4f0 2020-10-07)
 - Your PyO3 version: pyo3 = "0.13.2"
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: tried, didn't work as expected, but different error:
```
thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`: The Python interpreter is not initalized and the `auto-initialize` feature is not enabled.', /home/incomplete/.cargo/git/checkouts/pyo3-a22e69bc62b9f0fd/b68bc48/src/gil.rs:248:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:429
   2: pyo3::gil::GILGuard::acquire::{{closure}}
             at /home/incomplete/.cargo/git/checkouts/pyo3-a22e69bc62b9f0fd/b68bc48/src/gil.rs:248
   3: parking_lot::once::Once::call_once_force::{{closure}}
             at /home/incomplete/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.11.1/src/once.rs:189
   4: parking_lot::once::Once::call_once_slow
             at /home/incomplete/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.11.1/src/once.rs:304
   5: parking_lot::once::Once::call_once_force
             at /home/incomplete/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.11.1/src/once.rs:188
   6: pyo3::gil::GILGuard::acquire
             at /home/incomplete/.cargo/git/checkouts/pyo3-a22e69bc62b9f0fd/b68bc48/src/gil.rs:244
   7: pyo3::python::Python::acquire_gil
             at /home/incomplete/.cargo/git/checkouts/pyo3-a22e69bc62b9f0fd/b68bc48/src/python.rs:185
   8: play::main::{{closure}}
             at ./src/main.rs:10
```

### 💥 Reproducing

```
use pyo3::prelude::*;

fn main() {
    let main_barrier = std::sync::Arc::new(std::sync::Barrier::new(2));
    let worker_barrier = main_barrier.clone();

    // when D is commented out: 
    // - leaving A uncommented, B C commented will blocking the whole process from exiting
    // - leaving A commented out, B xor C uncommented, the code works as expected: the whole process exits
    // when D is uncommented:
    // all of A B C works as expected (the whole process exits)
    // according to https://doc.rust-lang.org/std/thread/fn.spawn.html
    // when the main threads exits, the whole process exits,
    // so the correct behaviour should be the ones exhibited by either B or C

    let _ = std::thread::spawn(move || {
        // { // D: if this bracket is uncommented then the tensorflow import also works fine

        let gil = Python::acquire_gil();

        let py = gil.python();

        // A: this will prevent the entire process from exiting
        let _ = py.import("tensorflow").unwrap();
        // In [34]: tensorflow.__version__
        // Out[34]: '2.4.1'

        // B: this will not prevent the entire process from exiting
        // let _ = py.import("torch").unwrap();
        // In [32]: torch.__version__
        // Out[32]: '1.7.1'

        // C: this will not prevent the entire process from exiting
        // let _ = py.import("numpy").unwrap();
        // In [36]: np.__version__
        // Out[36]: '1.20.0'

        // }

        println!("python module imported");

        worker_barrier.wait();

        loop {
            std::thread::sleep(std::time::Duration::from_secs(5));
        }
    });

    main_barrier.wait();
    println!("main thread exiting");
}

```

Please also write what exact flags are required to reproduce your results.

Just `cargo build`, no additional flags.

**Comment by davidhewitt** [comment]
Hi @qwfy can you retry with a Python 3.8 (or lower) environment? Tensorflow doesn't support Python 3.9 yet, as far as I'm aware.

I could successfully run the above example with `A`, `B`, and `C` all enabled (and no `D`) on my machine with Python 3.8.

With Python 3.9 I could not install `tensorflow`, and so the example fails (and deadlocks) with 

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'Mod
uleNotFoundError'>, value: ModuleNotFoundError("No module named 'tensorflow'"), traceback: None }', sr
c/main.rs:24:41
```

**Comment by davidhewitt** [comment]
Also, regarding the different error on `master` - that's because the `auto-initialize` feature is not enabled by default from the next PyO3 version. You will need to enable it directly in your `Cargo.toml`.

**Comment by qwfy** [comment]
@davidhewitt  I've tried tensorflow 1.14.0 with python 3.6.9 on ubuntu 18.04 with both pyo3 0.13.2 and pyo3 commit 593be05b from master, they all worked as expected (the process exits).

I guess it's a version mismatch between python and tf then, sorry for the noise.
