### ISSUE TITLE
word count example: setup throws error

### ISSUE THREAD

**Issue by ikamensh** [PyO3/pyo3#1477]
I have cloned this repository, and tried to run example 'word_count'. It didn't work:

38f9d3a65222:word-count ikkamens$ python setup.py install
running install
running bdist_egg
running egg_info
writing word_count.egg-info/PKG-INFO
writing dependency_links to word_count.egg-info/dependency_links.txt
writing top-level names to word_count.egg-info/top_level.txt
reading manifest file 'word_count.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'word_count.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.14-x86_64/egg
running install_lib
running build_py
running build_ext
running build_rust
error: failed to read `/Users/ikkamens/pyo3/examples/.DS_Store/Cargo.toml`

Caused by:
  Not a directory (os error 20)
Traceback (most recent call last):
  File "setup.py", line 92, in <module>
    'sdist': CargoModifiedSdist,
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/setuptools_rust/build_ext.py", line 26, in run
    build_rust.run()
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/setuptools_rust/build.py", line 313, in run
    self.build_extension(ext)
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/site-packages/setuptools_rust/build.py", line 95, in build_extension
    metadata = json.loads(check_output(metadata_command).decode("utf-8"))
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/Users/ikkamens/.pyenv/versions/3.6.8/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.

System info:

macOS Mojave
Version 10.14.5

38f9d3a65222:word-count ikkamens$ cargo -V
cargo 1.37.0-nightly (4c1fa54d1 2019-06-24)

38f9d3a65222:word-count ikkamens$ pip freeze | grep rust
setuptools-rust==0.10.6
38f9d3a65222:word-count ikkamens$ python -V
Python 3.6.8

Remark: the setup has worked once before this, but some files were missing as imports of external objects (rust compiled lib) failed, so I have deleted .egg and other generated files. Now I am getting this issue.

**Comment by davidhewitt** [comment]
Moved from `setuptools-rust` as is related to building the pyo3 example.
