### ISSUE TITLE
fails on build_rust due to failed to read pyo3/examples/.DS_Store/Cargo.toml

### ISSUE THREAD

**Issue by devdoomari3** [PyO3/pyo3#1478]
I'm using pyenv (python 3.7.2) with virtualenv. (MacOS 10.14 Mojave)

steps to reproduce:
- 1. clone PyO3 on my workspace
- 2. go to PyO3/examples/word-count
- 3. run `python setup.py install`

this fails with:
 
```
error: failed to read `/Users/myusername/Desktop/ruststuff/pyo3/examples/.DS_Store/Cargo.toml`

Caused by:
  Not a directory (os error 20)
Traceback (most recent call last):
  File "setup.py", line 53, in <module>
    cmdclass=dict(test=PyTest),
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/site-packages/setuptools_rust/build_ext.py", line 26, in run
    build_rust.run()
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/site-packages/setuptools_rust/build.py", line 313, in run
    self.build_extension(ext)
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/site-packages/setuptools_rust/build.py", line 95, in build_extension
    metadata = json.loads(check_output(metadata_command).decode("utf-8"))
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Users/myusername/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
```

**Comment by davidhewitt** [comment]
Transferred to PyO3 as it's related to building the example.
