### ISSUE TITLE
Instance can not use deepcopy

### ISSUE THREAD

**Issue by yanganto** [PyO3/pyo3#181]
## 🐛 Bug Reports

The instance made by class written in pyo3 cannot be deep copied.

### 🌍 Environment

 - ArchLinux
 - Python 3.6.5 installed
 - rustup 1.11.0
 - rustc 1.28.0-nightly (2a0062974 2018-06-09)

### 💥 Reproducing
```
#![feature(proc_macro, specialization)]
#[macro_use]
extern crate pyo3;

use pyo3::prelude::*;

use pyo3::py::class;

#[class]
struct MyClass{
    #[prop(get)]
    title: String,
    #[prop(get)]
    num: i32,
    #[prop(get)]
    words: Vec<String>
}
```
It will got following error message.

The instance can not use copy.deepcopy.
```
Python 3.6.5 (default, May 11 2018, 04:00:52)
[GCC 8.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import copy
>>> import my_class.MyClass as C
>>> c = C()
>>> c2 = copy.deepcopy(c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle my_class._my_class.MyClass objects
```

If there is any better practice please tell me.
Thank you.

**Comment by konstin** [comment]
Closing in favor of #100
