### ISSUE TITLE
Sporadic segfault on test_gc

### ISSUE THREAD

**Issue by ijl** [PyO3/pyo3#198]
I have the below error when running tests without `--test-threads=1`, e.g., the default or  `RUST_BACKTRACE=full cargo test --features python3 --no-default-features -- --test-threads=8`. It doesn't happen when using a single thread. It happens maybe one in twenty runs.

```
Running target/debug/deps/test_gc-a5a51037f354cb8a
running 7 tests
test class_with_freelist ... ok
test create_pointers_in_drop ... ok
test inheritance_with_new_methods_with_drop ... ok
test data_is_dropped ... ok
error: process didn't exit successfully: `pyo3/target/debug/deps/test_gc-a5a51037f354cb8a` (signal: 11, SIGSEGV: invalid memory reference
```

**Comment by pganssle** [comment]
So I've done some debugging on this, here's a backtrace:

<details>

```
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff7b20d24 in ?? () from /usr/lib/libpython3.7m.so.1.0
#2  0x00007ffff7b21bb1 in ?? () from /usr/lib/libpython3.7m.so.1.0
#3  0x00007ffff7c43230 in ?? () from /usr/lib/libpython3.7m.so.1.0
#4  0x00007ffff7b6e07c in _PyMethodDef_RawFastCallKeywords () from /usr/lib/libpython3.7m.so.1.0
#5  0x00007ffff7b6e201 in _PyCFunction_FastCallKeywords () from /usr/lib/libpython3.7m.so.1.0
#6  0x00007ffff7be3f5d in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.7m.so.1.0
#7  0x00007ffff7b26069 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.7m.so.1.0
#8  0x00007ffff7b26f34 in PyEval_EvalCodeEx () from /usr/lib/libpython3.7m.so.1.0
#9  0x00007ffff7b26f5c in PyEval_EvalCode () from /usr/lib/libpython3.7m.so.1.0
#10 0x00007ffff7c55770 in ?? () from /usr/lib/libpython3.7m.so.1.0
#11 0x00007ffff7c5701d in PyRun_StringFlags () from /usr/lib/libpython3.7m.so.1.0
#12 0x00005555555ec77f in pyo3::python::Python::run_code (self=..., code=..., start=257, globals=..., locals=...) at src/python.rs:202
#13 0x00005555555ec3ee in pyo3::python::Python::run (self=..., code=..., globals=..., locals=...) at src/python.rs:173
#14 0x0000555555568937 in test_gc::gc_integration () at tests/test_gc.rs:173
#15 0x00005555555a458a in test_gc::__test::TESTS::{{closure}} () at tests/test_gc.rs:154
#16 0x0000555555587a5e in core::ops::function::FnOnce::call_once () at /checkout/src/libcore/ops/function.rs:223
#17 0x00005555555ade1f in test::run_test::{{closure}} () at libtest/lib.rs:1459
#18 core::ops::function::FnOnce::call_once () at /checkout/src/libcore/ops/function.rs:223
#19 <F as alloc::boxed::FnBox<A>>::call_box () at /checkout/src/liballoc/boxed.rs:642
#20 0x000055555561b15a in __rust_maybe_catch_panic () at libpanic_unwind/lib.rs:102
#21 0x00005555555b997e in std::panicking::try () at /checkout/src/libstd/panicking.rs:289
#22 std::panic::catch_unwind () at /checkout/src/libstd/panic.rs:392
#23 test::run_test::run_test_inner::{{closure}} () at libtest/lib.rs:1414
#24 std::sys_common::backtrace::__rust_begin_short_backtrace () at /checkout/src/libstd/sys_common/backtrace.rs:136
#25 0x00005555555d2335 in std::thread::Builder::spawn::{{closure}}::{{closure}} () at /checkout/src/libstd/thread/mod.rs:409
#26 <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once () at /checkout/src/libstd/panic.rs:313
#27 std::panicking::try::do_call () at /checkout/src/libstd/panicking.rs:310
#28 0x000055555561b15a in __rust_maybe_catch_panic () at libpanic_unwind/lib.rs:102
#29 0x00005555555c3a27 in std::panicking::try () at /checkout/src/libstd/panicking.rs:289
#30 std::panic::catch_unwind () at /checkout/src/libstd/panic.rs:392
#31 std::thread::Builder::spawn::{{closure}} () at /checkout/src/libstd/thread/mod.rs:408
#32 <F as alloc::boxed::FnBox<A>>::call_box () at /checkout/src/liballoc/boxed.rs:642
#33 0x000055555560d5db in _$LT$alloc..boxed..Box$LT$$LP$dyn$u20$alloc..boxed..FnBox$LT$A$C$$u20$Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h904fcd0dbdc71d4f () at /checkout/src/liballoc/boxed.rs:652
#34 std::sys_common::thread::start_thread () at libstd/sys_common/thread.rs:24
#35 0x00005555555fdd36 in std::sys::unix::thread::Thread::new::thread_start () at libstd/sys/unix/thread.rs:90
#36 0x00007ffff79f5a9d in start_thread () from /usr/lib/libpthread.so.0
#37 0x00007ffff790ba43 in clone () from /usr/lib/libc.so.6
```

</details>

The offending function is [gc_integration](https://github.com/PyO3/pyo3/blob/master/tests/test_gc.rs#L154). I believe it's in a race condition with [gc_integration2](https://github.com/PyO3/pyo3/blob/master/tests/test_gc.rs#L182), which indirectly leads to some dereference of a null pointer.
