### ISSUE TITLE
Descriptor __get__ fails on class

### ISSUE THREAD

**Issue by gertjanvanzwieten** [PyO3/pyo3#1994]
### Bug Description

There seems to be an issue with PyO3's handling of the `__get__` method of a descriptor class when it is invoked on the class rather than the instance, in which case it raises a PanicException. The issue is common to both pyproto and (as of PyO3 0.15) pymethods.

A typical scenario in which the issue manifests is in code introspection by a tool such as Sphinx.

### Steps to Reproduce

The following minimal example (requiring PyO3 0.15) serves to demonstrate the issue:

```rust
use pyo3::prelude::*;

#[pyclass]
struct MyClass;

#[pymethods]
impl MyClass {
    #[new]
    fn __new__() -> Self { Self }
    fn __get__(_self: PyObject, instance: PyObject, _owner: PyObject) -> PyResult<PyObject> { Ok(instance) }
}

#[pymodule]
fn mymodule(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_class::<MyClass>()?;
    Ok(())
}
```

First, the expected behaviour:

```python
class MyClass: __get__ = lambda self, instance, owner: instance
class A: attr = MyClass()
print(A().attr) # <__main__.A object at 0x...>
print(A.attr) # None
print(MyClass().__get__(None, object)) # None
```

Then, taking `MyClass` from `mymodule`:

```python
from mymodule import MyClass
class A: attr = MyClass()
print(A().attr) # <__main__.A object at 0x...>
print(A.attr) # pyo3_runtime.PanicException: Python API call failed
print(MyClass().__get__(None, object)) # pyo3_runtime.PanicException: Python API call failed
```

As seen above, getting `attr` from an instance works as intended, but getting it from the class raises an exception, as does calling `__get__` directly with a `None` instance.

### Backtrace

```shell
thread '<unnamed>' panicked at 'Python API call failed', .../pyo3-0.15.0/src/err/mod.rs:582:5
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/.../library/std/src/panicking.rs:525:12
   1: pyo3::err::panic_after_error
             at .../pyo3-0.15.0/src/err/mod.rs:582:5
   2: pyo3::conversion::FromPyPointer::from_borrowed_ptr_or_panic::{{closure}}
             at .../pyo3-0.15.0/src/conversion.rs:512:67
   3: core::option::Option<T>::unwrap_or_else
             at /rustc/.../library/core/src/option.rs:787:21
   4: pyo3::conversion::FromPyPointer::from_borrowed_ptr_or_panic
             at .../pyo3-0.15.0/src/conversion.rs:512:9
   5: pyo3::conversion::FromPyPointer::from_borrowed_ptr
             at .../pyo3-0.15.0/src/conversion.rs:520:9
   6: pyo3::python::Python::from_borrowed_ptr
             at .../pyo3-0.15.0/src/python.rs:645:9
   7: mymodule::<impl pyo3::class::impl_::PyMethodsProtocolSlots<mymodule::MyClass> for pyo3::class::impl_::PyClassImplCollector<mymodule::MyClass>>
::methods_protocol_slots::__wrap::{{closure}}
             at ./src/lib.rs:6:1
   8: pyo3::callback::handle_panic::{{closure}}
             at .../pyo3-0.15.0/src/callback.rs:247:9
   9: std::panicking::try::do_call
             at /rustc/.../library/std/src/panicking.rs:406:40
  10: __rust_try
  11: std::panicking::try
             at /rustc/.../library/std/src/panicking.rs:370:19
  12: std::panic::catch_unwind
             at /rustc/.../library/std/src/panic.rs:133:14
  13: pyo3::callback::handle_panic
             at .../src/callback.rs:245:24
  14: mymodule::<impl pyo3::class::impl_::PyMethodsProtocolSlots<mymodule::MyClass> for pyo3::class::impl_::PyClassImplCollector<mymodule::MyClass>>
::methods_protocol_slots::__wrap
             at ./src/lib.rs:6:1
```

### Your operating system and version

Debian Linux

### Your Python version (`python --version`)

Python 3.9.2

### Your Rust version (`rustc --version`)

rustc 1.55.0 (c8dfcfe04 2021-09-06)

### Your PyO3 version

0.15.0

### How did you install python? Did you use a virtualenv?

apt

**Comment by davidhewitt** [comment]
Thanks for the comprehensive report. I've played around with this a bit and can repro. Looks like this null-pointer passing is unique to the `__get__` implementation.
