### ISSUE TITLE
undefined symbol: PyList_New when loading a Python script from shared library that embedds PyO3 interpreter on Linux

### ISSUE THREAD

**Issue by gabrik** [PyO3/pyo3#2024]
### Bug Description

When loading a python script from a `.so` crate that uses PyO3 to call functions it does not run and returns an undefined symbol error.

When the same python script is loaded from an `executable` that uses exactly the same code the script is able to run.

This happens in Linux (Ubuntu 20.04 - Python3.8 and Debian 9 - Python3.7), on macOS everything seems to work.

### Steps to Reproduce

It can be easily reproduced using the python bindings we are building for our code.
1. clone and build the bindings:
```
$ git clone https://github.com/atolab/zenoh-flow-python
$ cd zenoh-flow-python/zenoh-flow-python
$ pip3 install -r requirements-dev.txt
$ python3 setup.py bdist_wheel
$ pip3 install dist/eclipse_zenoh_flow-0.1.0-cp36-abi3-linux_x86_64.whl
$ cd ..
$ cargo build -p py-source -p py-sink -p py-op
```
2. clone and build a runtime
```
$ git clone https://github.com/atolab/zenoh-flow-examples
$ cd zenoh-flow-examples
$ cargo build -p runtime
```

3. run the example and let it fails
```
$ cd zenoh-flow-python
$ ../zenoh-flow-examples/target/debug/runtime -r debug -g py-pipeline.yml -l loader-config.yml
...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidData("ImportError: /home/luca/.local/lib/python3.8/site-packages/zenoh_flow.abi3.so: undefined symbol: PyList_New")', runtime/src/main.rs:92:87
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

### Your operating system and version

Ubuntu 20.04

### Your Python version (`python --version`)

Python 3.8.10

### Your Rust version (`rustc --version`)

rustc 1.56.1 (59eed8a2a 2021-11-01)

### Your PyO3 version

0.15

### How did you install python? Did you use a virtualenv?

apt

### Additional Info

I made a simple executable that uses the same calls done by the `.so` generated in the `zenoh-flow-python` wrappers.
And calling one of the examples works, also on macOS everything seems working just fine.
Both the `.so` and the `executable`  seems to have the same dynamic linking with the python3.8 library.
The `executable` is in this repo: https://github.com/gabrik/zenoh-ifttt-demo as py-test
**.so**
```
$ ldd target/debug/libpy_sink.so
	linux-vdso.so.1 (0x00007ffc4a7c9000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa7a45cf000)
	libpython3.8.so.1.0 => /lib/x86_64-linux-gnu/libpython3.8.so.1.0 (0x00007fa7a4079000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa7a405e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa7a4053000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa7a4030000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa7a3edf000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa7a3ced000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa7a470c000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fa7a3cbf000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa7a3ca3000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fa7a3c9e000)
```

**executable**
```
ldd ../zenoh-ifttt-demo/py-test/target/debug/py-test
	linux-vdso.so.1 (0x00007ffd7e15e000)
	libpython3.8.so.1.0 => /lib/x86_64-linux-gnu/libpython3.8.so.1.0 (0x00007f0456dae000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0456d93000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0456d70000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0456c21000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0456c1b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0456a27000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f04573be000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f04569f9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f04569dd000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f04569d8000)
```

**Comment by gabrik** [comment]
**Update**

I was able to create a simpler example that can be used to reproduce this bug.
Here the steps to reproduce it:

1. Install our python bindings like in step 1 of the previous message.
2. clone and build the simpler example

```
$ git clone https://github.com/gabrik/zenoh-ifttt-demo
$ cd zenoh-ifttt-demo
$ cargo build --manifest-path loader/Cargo.toml
$ cargo build --manifest-path wrapper/Cargo.toml
$ cargo build --manifest-path py-test/Cargo.toml
```

Run the working one (*executable* calling python):
```
$ ./py-test/target/debug/py-test py-sink.py
Data b'Hello'
Data b'Hello'
....
```

Run the not working one (*executable* loading *.so* calling python):
```
$ ./loader/target/debug/main ./wrapper/target/debug/libwrapper.so py-sink.py
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ImportError'>, value: ImportError('/home/luca/.local/lib/python3.8/site-packages/zenoh_flow.abi3.so: undefined symbol: PyList_New'), traceback: Some(<traceback object at 0x7f6c1bf29cc0>) }', src/lib.rs:28:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This example works on macOS, but gives this behavior in Linux machines.
Any idea?

**Comment by gabrik** [comment]
*Update* it seems to not work with any `module` that is binary, I tried to just run this very simple script and the error is quite similar.

```
def main():
    import time
    import numpy
    # bs = BasicSink()
    # state = bs.initialize({})
    while True:
        time.sleep(1)
        # bs.run(None, state, b'Hello')
        data = b'Hello'
        print(f'Data {data}')
if __name__=='__main__':
    main()
```
This is the result,
```
$ ./loader/target/debug/main ./wrapper/target/debug/libwrapper.so simple.py
Python TraceBack: Traceback (most recent call last):
  File "op.py", line 36, in main
  File "/home/luca/.local/lib/python3.8/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/home/luca/.local/lib/python3.8/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)

thread '<unnamed>' panicked at 'ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/usr/bin/python3"
  * The NumPy version is: "1.21.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /home/luca/.local/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyExc_RecursionError
', src/lib.rs:32:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```


While with the *executable* wrapper it work...
```
$ ./py-test/target/debug/py-test simple.py
Data b'Hello'
Data b'Hello'
...
```

So I'm little bit confused....

**Comment by davidhewitt** [comment]
Sorry for the slow reply. I've taken a quick look at your demo. Going through the `libloading` crate is probably the cause? Opening a shared library using `libloading` won't load its symbols to the process address space by default.

Changing this line 

```
let library = Library::new(path).unwrap();
```

to the following might help?

```
let library = Library::open(path, libloading::os::unix::RTLD_NOW | libloading::os::unix::RTLD_GLOBAL).unwrap();
```

`RTLD_GLOBAL` flag in particular will pull all the symbols from that library into the process address space, which should let the python extensions you're trying to import see the symbols.

It may not be enough to do this for the wrapper library; you might have to do this for `libpython` itself.

(This is actually quite similar to #2000 which used `libloading` to solve a related issue.)

**Comment by davidhewitt** [comment]
(Maybe #2033 is also relevant for you if you need to locate libpython to load it.)

**Comment by gabrik** [comment]
@davidhewitt thank you! 

Using the `Library::open` works, I guess we can close this.

Thank you again!
