### ISSUE TITLE
PyPy: ModuleNotFoundError with Rust library

### ISSUE THREAD

**Issue by codeandfire** [PyO3/pyo3#2394]
### Bug Description

While using PyPy, a compiled `.so` Rust library placed in the directory containing the Python source code fails to get imported and results in a `ModuleNotFoundError`. This does not happen while using the regular Python interpreter (CPython): the module gets imported successfully.

### Steps to Reproduce

Please refer to [this repository](https://github.com/codeandfire/helloworld) which serves as a MWE.

Then while using the regular Python interpreter:
```
$ export PYO3_PYTHON=python3.10
$ cargo build --lib
$ cp ./target/debug/libhelloworld.so ./src/helloworld/helloworld.so
$ cd src && python3 -m helloworld
Hello, world!
```
whereas while using PyPy:
```
$ export PYO3_PYTHON=pypy3
$ cargo build --lib
$ cp ./target/debug/libhelloworld.so ./src/helloworld/helloworld.so
$ cd src && pypy3 -m helloworld
Traceback (most recent call last):
  File "/opt/pypy3/lib/pypy3.8/runpy.py", line 198, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/pypy3/lib/pypy3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/codeandfire/helloworld/src/helloworld/__main__.py", line 1, in <module>
    from .helloworld import hello_world
ModuleNotFoundError: No module named 'helloworld.helloworld'
```

### Your operating system and version

Arch Linux. Linux kernel 5.17.7

### Your Python version (`python --version`)

CPython 3.10.4, PyPy 3.8.13

### Your Rust version (`rustc --version`)

1.60.0

### Your PyO3 version

0.16.4

### How did you install python? Did you use a virtualenv?

Pacman.

I did not use a virtualenv for this MWE since it had no dependencies. However I can confirm that the same behaviour occurs inside a virtualenv as well.

### Additional Info

I have tried enabling the `extension-module` feature, as well as the `abi3-py38` feature, but with the same result.

**Comment by davidhewitt** [comment]
I suspect that pypy ignores `.so` extension by default (assuming they are for CPython), and instead requires the platform tag e.g. `pypy36-pp73-x86_64-linux-gnu.so`.

If you compile with setuptools-rust or maturin, you should see the platform tag they are using. Then you could rename your library as appropriate and retry?

**Comment by codeandfire** [comment]
@davidhewitt thanks for your response!

I tried your suggestion, but it's still not working for me. Here is a trace of what I have tried:
```
$ export PYO3_PYTHON=pypy3
$ pypy3 -m venv .venv
$ source .venv/bin/activate
(.venv) $ pypy3 -m pip install maturin
Collecting maturin
  Using cached maturin-0.12.17-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (9.2 MB)
Collecting tomli>=1.1.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Installing collected packages: tomli, maturin
Successfully installed maturin-0.12.17 tomli-2.0.1
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the '/home/codeandfire/helloworld/.venv/bin/pypy3 -m pip install --upgrade pip' command.
(.venv) $ maturin develop
🔗 Found pyo3 bindings
🐍 Found PyPy 3.8 at /home/codeandfire/helloworld/.venv/bin/python
   Compiling pyo3-build-config v0.16.5
   Compiling pyo3-ffi v0.16.5
   Compiling pyo3 v0.16.5
   Compiling helloworld v0.1.0 (/home/codeandfire/helloworld)
    Finished dev [unoptimized + debuginfo] target(s) in 3.41s
📦 Built wheel for PyPy 3.8 to /tmp/.tmpczDdq7/helloworld-0.1.0-pp38-pypy38_pp73-linux_x86_64.whl
🛠  Installed helloworld-0.1.0
(.venv) $ deactivate 
$ rm -r .venv 
$ cargo build --lib
   Compiling pyo3-build-config v0.16.5
   Compiling pyo3-ffi v0.16.5
   Compiling pyo3 v0.16.5
   Compiling helloworld v0.1.0 (/home/codeandfire/helloworld)
    Finished dev [unoptimized + debuginfo] target(s) in 4.03s
$ cp ./target/debug/libhelloworld.so ./src/helloworld/helloworld-0.1.0-pp38-pypy38_pp73-linux_x86_64.so
$ cd src && pypy3 -m helloworld
Traceback (most recent call last):
  File "/opt/pypy3/lib/pypy3.8/runpy.py", line 198, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/pypy3/lib/pypy3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/codeandfire/helloworld/src/helloworld/__main__.py", line 1, in <module>
    from .helloworld import hello_world
ModuleNotFoundError: No module named 'helloworld.helloworld'
$ cd ..
$ cp ./target/debug/libhelloworld.so ./src/helloworld/helloworld-pp38-pypy38_pp73-linux_x86_64.so
$ cd src && pypy3 -m helloworld                                                                  
Traceback (most recent call last):
  File "/opt/pypy3/lib/pypy3.8/runpy.py", line 198, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/pypy3/lib/pypy3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/codeandfire/helloworld/src/helloworld/__main__.py", line 1, in <module>
    from .helloworld import hello_world
ModuleNotFoundError: No module named 'helloworld.helloworld'
$ cd ..
$ cp ./target/debug/libhelloworld.so ./src/helloworld/helloworld-0.1.0-pypy38_pp73-linux_x86_64.so
$ cd src && pypy3 -m helloworld                                                                   
Traceback (most recent call last):
  File "/opt/pypy3/lib/pypy3.8/runpy.py", line 198, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/pypy3/lib/pypy3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/codeandfire/helloworld/src/helloworld/__main__.py", line 1, in <module>
    from .helloworld import hello_world
ModuleNotFoundError: No module named 'helloworld.helloworld'
```
As you can see I have tried three ways of renaming the library, but they don't seem to work.

**Comment by davidhewitt** [comment]
Comparing to some files on my machine, maybe try `helloworld.pypy38-pp73.x86_64-linux-gnu.so` ?

If that doesn't work - after building with maturin, you can also extract the wheel `helloworld-0.1.0-pp38-pypy38_pp73-linux_x86_64.whl` (rename it to `.zip` and then extract it trivially). Take a look in there to see what the built `.so` file is called, and use that?

**Comment by davidhewitt** [comment]
I think you might also be able to get the right suffix from `sysconfig`:

```python
>>> import sysconfig
>>> sysconfig.get_config_var("EXT_SUFFIX")
'.cpython-310-darwin.so'
```

**Comment by codeandfire** [comment]
The `sysconfig` trick works:
```python
>>>> import sysconfig
>>>> sysconfig.get_config_var('EXT_SUFFIX')
'.pypy38-pp73-x86_64-linux-gnu.so'
```
and then renaming the binary as `helloworld.pypy38-pp73-x86_64-linux-gnu.so` does the job. Thank you for your time!
