### ISSUE TITLE
`text_signature` with enum default arguments 

### ISSUE THREAD

**Issue by g-bauer** [PyO3/pyo3#2920]
We are using Sphinx to generate the documentation for our Python package that we build using pyO3. 
With the latest changes to `signature` and `text_signature`, we wanted to properly document default values for function and method arguments, including enum arguments. 

For example, we added a text signature like `text_signature ="(a=MyEnum.Variant1)"` where `MyEnum` is a Rust enum and `pyclass`. Sphinx (autodoc) is not able to parse these signatures - it crashes with an exception:

```
<function record_typehints at 0x7f90007ed3a0> for event 'autodoc-process-signature' threw an exception (exception: )
``` 

I wasn't able to figure out what exactly goes wrong here. If this is not an issue of PyO3 but Sphinx, feel free to close this issue.
I'd be grateful for help or ideas to resolve this. For now, we removed the defaults in `text_signature` (`signature` works fine) but that's not an ideal solution.

I built a small crate that reproduces the error [here](https://github.com/g-bauer/test_enum_args).

**Comment by davidhewitt** [comment]
It seems like this is not sphinx's fault so much as `inspect.signature`. I took a look at the `record_typehints` function in sphinx, which calls this.

I got the following crash from your repro (great repro, many thanks):

```python
>>> inspect.signature(test_enum_args.variant_string)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py", line 3253, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py", line 3001, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py", line 2467, in _signature_from_callable
    return _signature_from_builtin(sigcls, obj,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py", line 2276, in _signature_from_builtin
    return _signature_fromstr(cls, func, s, skip_bound_arg)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py", line 2224, in _signature_fromstr
    p(name, default)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py", line 2206, in p
    default_node = RewriteSymbolics().visit(default_node)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py", line 2193, in visit_Attribute
    return wrap_value(value)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/inspect.py", line 2180, in wrap_value
    raise RuntimeError()
RuntimeError
```

If we can understand why `inspect.signature` crashes (possibly with fix upstream in CPython?) then we can resolve this.
