### ISSUE TITLE
Extending native types does not always work

### ISSUE THREAD

**Issue by AntoineRR** [PyO3/pyo3#2942]
### Bug Description

I tried to extend various classes implementing [PySizedLayout](https://docs.rs/pyo3/latest/pyo3/type_object/trait.PySizedLayout.html) as stated in the [docs](https://pyo3.rs/v0.18.1/class#inheritance), but it seems only a few of those classes can be used as base class. I tried:
- `PyDict` and `PySet`, which work fine.
- `PyBool` and `PySlice`, which gives this error: `TypeError: type 'bool' (or 'slice') is not an acceptable base type`
- Most importantly, `PyFloat` and `PyFrozenSet` give the following: `Job 1, 'python3 test.py' terminated by signal SIGSEGV (Address boundary error)`

### Steps to Reproduce

1. Cargo.toml

```toml
[package]
name = "pyo3_test"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { git = "https://github.com/PyO3/pyo3", features = ["extension-module"] }

[lib]
name = "pyo3_test"

crate-type = ["cdylib"]
```

2. Rust code:

```rust
use pyo3::types::PyFloat;
use pyo3::PyAny;
use pyo3::{pyclass, pymethods, pymodule, types::PyModule, PyResult, Python};

#[pyclass(extends=PyFloat)] // Or replace with other Py* struct
struct Number;

#[pymethods]
impl Number {
    #[new]
    #[pyo3(signature = (*_args, **_kwargs))]
    pub fn new(_args: &PyAny, _kwargs: Option<&PyAny>) -> Self {
        Self {}
    }
}

#[pymodule]
fn pyo3_test(_py: Python<'_>, m: &PyModule) -> PyResult<()> {
    m.add_class::<Number>()?;
    Ok(())
}
```

3. Python code:

```python
from pyo3_test import Number

test = Number()

print(test)
```

4. Commands (inside venv)

```
$ maturin develop
$ python3 test.py
```

### Backtrace

```shell
For PyFloat for example:

fish: Job 1, 'python3 test.py' terminated by signal SIGSEGV (Address boundary error)

and for PySlice:

TypeError: type 'slice' is not an acceptable base type
thread '<unnamed>' panicked at 'An error occurred while initializing class Number', /home/<user>/.cargo/git/checkouts/pyo3-a22e69bc62b9f0fd/6757391/src/pyclass.rs:412:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/<user>/<path>/pyo3-test/test.py", line 1, in <module>
    from pyo3_test import Number
  File "/home/<user>/<path>/pyo3-test/venv/lib/python3.10/site-packages/pyo3_test/__init__.py", line 1, in <module>
    from .pyo3_test import *
pyo3_runtime.PanicException: An error occurred while initializing class Number
```

### Your operating system and version

PopOS 22.04

### Your Python version (`python --version`)

Python 3.10.6

### Your Rust version (`rustc --version`)

rustc 1.67.0 (fc594f156 2023-01-24)

### Your PyO3 version

master

### How did you install python? Did you use a virtualenv?

python installed with apt (IIRC) and using a venv.

**Comment by davidhewitt** [comment]
Thanks for the report.

So regarding the case when the type isn't allowed to be subclassed, we can't change that property but we _can_ rework the panic into an exception.

The segfault is a bit messier, I'll need to investigate and think about this.
