### ISSUE TITLE
musllinux python3.11 broken wheel

### ISSUE THREAD

**Issue by MartinoMensio** [PyO3/pyo3#3080]
### Bug Description

Hi, 
Thanks for the great resource.
I am testing musllinux builds, and I am currently unable to generate working wheels for python3.11. When I use python3.10 or lower, the compilation works as expected.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/maturin_musl_fail/__init__.py", line 1, in <module>
    from .maturin_musl_fail import *
ModuleNotFoundError: No module named 'maturin_musl_fail.maturin_musl_fail'
```

I am not sure if this is a pyo3 isssue or a maturin issue, so please if this is not the correct place, just let me know.

Best,
Martino

### Steps to Reproduce

1. I created this minimal example repository: https://github.com/MartinoMensio/maturin_musl_fail with the code generated with `maturin init`
2. I build the wheels with GitHub Actions, and they are generated successfully https://github.com/MartinoMensio/maturin_musl_fail/actions/runs/4608410699#artifacts
3. I download the wheels and I run the following code:

```bash
# tested broken on platforms linux/amd64 and linux/386 with alpine (musllinux) 
docker run --rm -it --platform=linux/amd64 -v `pwd`/wheels:/wheels python:3.11-alpine sh
# then inside install wheel (everything ok)
pip install wheels/maturin_musl_fail-0.1.0-cp311-cp311-musllinux_1_1_x86_64.whl
# then test import
python -c "import maturin_musl_fail; print('import ok')"
```

The last step generates:
```text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/maturin_musl_fail/__init__.py", line 1, in <module>
    from .maturin_musl_fail import *
ModuleNotFoundError: No module named 'maturin_musl_fail.maturin_musl_fail'
```

### Backtrace

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/maturin_musl_fail/__init__.py", line 1, in <module>
    from .maturin_musl_fail import *
ModuleNotFoundError: No module named 'maturin_musl_fail.maturin_musl_fail'
```

### Your operating system and version

MacOS Ventura 13.3

### Your Python version (`python --version`)

python 3.11

### Your Rust version (`rustc --version`)

rustc 1.68.2 (9eb3afe9e 2023-03-27)

### Your PyO3 version

0.18.1

### How did you install python? Did you use a virtualenv?

Buildtime:
github actions

Runtime generating error:
docker: python:3.11-alpine

**Comment by MartinoMensio** [comment]
After analysing the generated `.so` files and reading the guide here: https://pyo3.rs/main/building_and_distribution

I discovered that:
1. the generated wheel has a `.so` file with name `maturin_musl_fail.cpython-311-x86_64-linux-gnu.so`
2. running `python -c 'import sysconfig; print(sysconfig.get_config_var("EXT_SUFFIX"))'` generates `.cpython-311-x86_64-linux-musl.so`
3. renaming the `.so` file to `maturin_musl_fail.cpython-311-x86_64-linux-musl.so` (changing `gnu` to `musl`) solves the issue and I can load the module.

Therefore I will now try to understand the source code of https://github.com/PyO3/maturin-action as it's probably what is setting the `EXT_SUFFIX` wrongly.

Any help understanding this is appreciated :)

Best,
Martino

**Comment by messense** [comment]
See https://github.com/pypa/auditwheel/issues/349, probably alpine updated `SOABI` on python 3.11, we may have to update in `maturin` too.
