### ISSUE TITLE
Downcast semantics changed between 0.20 and `main`

### ISSUE THREAD

**Issue by Icxolu** [PyO3/pyo3#3929]
Since we're on the final stretch to 0.21, I've started to prepare a commit to kickoff the migration over at [`rust-numpy`](https://github.com/PyO3/rust-numpy). I've only made the minimal changes necessary to compile against pyo3 `main` (`70a7aa8`). The diff can be found over [here](https://github.com/Icxolu/rust-numpy/commit/4c89f5aba8e48c135bdac2ae4af86a307cdfaf83).

I've used this `.cargo/config.toml`:
```toml
[patch.crates-io]
pyo3 = { git = "https://github.com/PyO3/pyo3.git", branch = "main" }
```

This went pretty smooth overall, but running the tests showed 3 failures: 
- `unicode_strings_respect_byteorder`
   https://github.com/PyO3/rust-numpy/blob/32740b33ec55ef0b7ebec726288665837722841d/tests/array.rs#L725-L754
- `downcasting_respects_dimensionality`
   https://github.com/PyO3/rust-numpy/blob/32740b33ec55ef0b7ebec726288665837722841d/tests/array.rs#L441-L448
- `downcasting_respects_element_type`
   https://github.com/PyO3/rust-numpy/blob/32740b33ec55ef0b7ebec726288665837722841d/tests/array.rs#L433-L439

```
---- unicode_strings_respect_byteorder stdout ----
thread 'unicode_strings_respect_byteorder' panicked at tests/array.rs:751:18:
Only native byteorder should work
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- downcasting_respects_dimensionality stdout ----
thread 'downcasting_respects_dimensionality' panicked at tests/array.rs:446:9:
assertion failed: ob.downcast::<PyArray2<i32>>().is_err()

---- downcasting_respects_element_type stdout ----
thread 'downcasting_respects_element_type' panicked at tests/array.rs:437:9:
assertion failed: ob.downcast::<PyArray1<f64>>().is_err()
```
These all have in common, that they check for downcasting _failures_, which do fail on 0.20, but now (incorrectly?) succeed on main. I assume this has to do with the switch from `PyTryFrom` to `PyTypeCheck`, but I have not checked.

I've tested this under WSL-Ubuntu with Python 3.12.1, `numpy` 1.26.4 and `ml-dtypes` 0.3.2

**Comment by Icxolu** [comment]
Thank you, that seems to work indeed! I guess the pitfall here was that I assumed that `is_type_of_bound` will default to `is_type_of` (and vice versa), like we have done for `FromPyObject`. A small note in the migration guide probably would not hurt, but I agree that that's probably enough if this is more of a niche use case.
