### ISSUE TITLE
Can't build on Windows 10

### ISSUE THREAD

**Issue by diegogangl** [PyO3/pyo3#414]
## 🐛 Bug Reports

When reporting a bug, please provide the following information. If this is not a bug report you can just discard this template.

### 🌍 Environment

 - Your operating system and version: Windows 10
 - Your python version: Python 3.7
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Installer
 - Your rust version (`rustc --version`):  1.35.0-nightly (94fd04589 2019-03-21)  
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` Yes

### 💥 Reproducing

1. First set LIB as the docs suggest

```
set LIB=C:\Users\januz\AppData\Local\Programs\Python\Python37\libs\python37.lib
```
(I've also tried setting lib to just the folder)

2. Run `cargo build`

```
error: failed to run custom build command for `pyo3 v0.6.0-alpha.4`
process didn't exit successfully: `C:\Users\januz\Desktop\rusty\target\debug\build\pyo3-91624baacf3f5837\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run the python interpreter at python: The system cannot find the file specified. (os error 2)"', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

Full backtrace:

```
error: failed to run custom build command for `pyo3 v0.6.0-alpha.4`
process didn't exit successfully: `C:\Users\januz\Desktop\rusty\target\debug\build\pyo3-91624baacf3f5837\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run the python interpreter at python: The system cannot find the file specified. (os error 2)"', src\libcore\result.rs:997:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\panicking.rs:474
   7: std::panicking::continue_panic_fmt
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\panicking.rs:381
   8: std::panicking::rust_begin_panic
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\panicking.rs:308
   9: core::panicking::panic_fmt
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libcore\panicking.rs:85
  10: core::result::unwrap_failed<alloc::string::String>
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\src\libcore\macros.rs:16
  11: core::result::Result<(build_script_build::PythonVersion, std::collections::hash::map::HashMap<alloc::string::String, alloc::string::String, std::collections::hash::map::RandomState>, alloc::vec::Vec<alloc::string::String>), alloc::string::String>::unwrap<(build_script_build::PythonVersion, std::collections::hash::map::HashMap<alloc::string::String, alloc::string::String, std::collections::hash::map::RandomState>, alloc::vec::Vec<alloc::string::String>),alloc::string::String>
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\src\libcore\result.rs:798
  12: build_script_build::main
             at .\build.rs:564
  13: std::rt::lang_start::{{closure}}<()>
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\src\libstd\rt.rs:64
  14: std::rt::lang_start_internal::{{closure}}
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\rt.rs:49
  15: std::panicking::try::do_call<closure,i32>
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\panicking.rs:293
  16: panic_unwind::__rust_maybe_catch_panic
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libpanic_unwind\lib.rs:87
  17: std::panicking::try
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\panicking.rs:272
  18: std::panic::catch_unwind
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\panic.rs:388
  19: std::rt::lang_start_internal
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\/src\libstd\rt.rs:48
  20: std::rt::lang_start<()>
             at /rustc/94fd0458951a4ff91c03366445f0e2e93b86bd2f\src\libstd\rt.rs:64
  21: main
  22: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  23: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  24: BaseThreadInitThunk
  25: RtlUserThreadStart
```

**Comment by konstin** [comment]
Have you checked that python is in `PATH` or tried using a virtualenv?The build script just tries to run `python`, so it fails if python is not in `PATH`

**Comment by diegogangl** [comment]
You're right, Python wasn't in `PATH`. I assumed it would be added automatically but looks like I missed the checkbox in the installer. Thanks! (sorry for reporting a non-bug)

**Comment by konstin** [comment]
I've tried to improve the error message to be more clear. This is how it looks now on my machine:

```
   Compiling pyo3 v0.6.0-alpha.4 (/home/konsti/pyo3)
error: failed to run custom build command for `pyo3 v0.6.0-alpha.4 (/home/konsti/pyo3)`
process didn't exit successfully: `/home/konsti/pyo3/target/debug/build/pyo3-bcc3e702033ec884/build-script-build` (exit code: 1)
--- stderr
Error: "Could not find any interpreter at python, are you sure you have python installed on your PATH?"
```

**Comment by diegogangl** [comment]
That's way better :+1:
