### ISSUE TITLE
Test failure on Mac free-threaded CI

### ISSUE THREAD

**Issue by ngoldbaum** [PyO3/pyo3#4688]
See https://github.com/PyO3/pyo3/actions/runs/11701201572/job/32586835300#step:11:3324

Ironically, in the run after we merged the PR adding the CI job. I've never seen this in my local development setup.

```
  failures:
  
  ---- coroutine_is_cancelled stdout ----
  thread 'coroutine_is_cancelled' panicked at tests/test_coroutine.rs:227:10:
  called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'asyncio.exceptions.CancelledError'>, value: CancelledError(), traceback: Some(<traceback object at 0x20000381880>) }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  
  
  failures:
      coroutine_is_cancelled
```

**Comment by ngoldbaum** [comment]
I just hit this on my local dev setup, which seems related:

```
---- coroutine_cancel_handle stdout ----
thread 'coroutine_cancel_handle' panicked at tests/test_coroutine.rs:197:10:
called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'AssertionError'>, value: AssertionError(), traceback: Some(<traceback object at 0x200040301c0>) }
```

I haven't seen it before and can't seem to trigger it again.

**Comment by ngoldbaum** [comment]
Haven't seen this in a while, closing.
