### ISSUE TITLE
examples/rustapi_module doesn't work on windows 10

### ISSUE THREAD

**Issue by ikamensh** [PyO3/pyo3#520]
## 🐛 Bug Reports

When reporting a bug, please provide the following information. If this is not a bug report you can just discard this template.

### 🌍 Environment

 - Your operating system and version: Windows 10
 - Your python version: 3.7.1
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: .exe installer, no virtualenv
 - Your rust version (`rustc --version`): rustc 1.37.0-nightly (088b98730 2019-07-03)
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`  latest (4th July 2019) from github

### 💥 Reproducing

```
git clone https://github.com/PyO3/pyo3.git
cd pyo3/examples/rustapi_module
pip install -r requirements-dev.txt
python setup.py install
```

Results in error:

```
   Compiling thread_local v0.3.6
     Running `rustc --crate-name thread_local C:\Users\Ilya\.cargo\registry\src\github.com-1ecc6299db9ec823\thread_local-0.3.6\src\lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=58f99430dde997ba -C extra-filename=-58f99430dde997ba --out-dir C:\Users\Ilya\pyo3\target\release\deps -L dependency=C:\Users\Ilya\pyo3\target\release\deps --extern lazy_static=C:\Users\Ilya\pyo3\target\release\deps\liblazy_static-6dd3ad9dfaa8ae94.rlib --cap-lints allow`
error: linking with `link.exe` failed: exit code: 1
  |
  = note: "link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.build_script_build.a0ws0y8s-cgu.0.rcgu.o" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.build_script_build.a0ws0y8s-cgu.1.rcgu.o" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.build_script_build.a0ws0y8s-cgu.10.rcgu.o" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.build_script_build.a0ws0y8s-cgu.11.rcgu.o" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.build_script_build.a0ws0y8s-cgu.12.rcgu.o" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.build_script_build.a0ws0y8s-cgu.2.rcgu.o" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.build_script_build.a0ws0y8s-cgu.3.rcgu.o" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.build_script_build.a0ws0y8s-cgu.4.rcgu.o" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.build_script_build.a0ws0y8s-cgu.5.rcgu.o" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.build_script_build.a0ws0y8s-cgu.6.rcgu.o" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.build_script_build.a0ws0y8s-cgu.7.rcgu.o" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.build_script_build.a0ws0y8s-cgu.8.rcgu.o" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.build_script_build.a0ws0y8s-cgu.9.rcgu.o" "/OUT:C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.exe" "C:\\Users\\Ilya\\pyo3\\target\\release\\build\\ryu-df18fbcd37d5d2bc\\build_script_build-df18fbcd37d5d2bc.2g2lb2pjrquyf5s1.rcgu.o" "/OPT:REF,ICF" "/DEBUG" "/NATVIS:C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:C:\\Users\\Ilya\\pyo3\\target\\release\\deps" "/LIBPATH:C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-2dfd7389b5876e86.rlib" "C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-5598aa78fec0426c.rlib" "C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libbacktrace-6e50467df9b422b0.rlib" "C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-297241552564d253.rlib" "C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-cb3e6545928e6214.rlib" "C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-4ed577709fb3bd8d.rlib" "C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-3d19960231ff2f86.rlib" "C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-57b11e7f9f4972b6.rlib" "C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-657b95965c47cda0.rlib" "C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-6d9697981d0586d9.rlib" "C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-6036d6352d0dbf49.rlib" "C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-34e946675445491c.rlib" "C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-d8d01caf624fbaac.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: /usr/bin/link: extra operand ‘/LIBPATH:C:\\Users\\Ilya\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib’
          Try '/usr/bin/link --help' for more information.


error: aborting due to previous error
```

**Comment by pganssle** [comment]
@ikamensh That is not the correct way to install the `rustapi_module`, and in fact in general invoking `setup.py install` is not the right way to install any python modules. The correct thing to do is this:

```bash
git clone https://github.com/PyO3/pyo3.git
cd pyo3/examples/rustapi_module
pip install .
```

(Though admittedly this is broken for me now for some unrelated reason.)

**Comment by ikamensh** [comment]
I have solved this problem by installing Visual Studio 2019 with C++ tools for windows.

**Comment by ikamensh** [comment]
@pganssle 

```
C:\Users\Ilya\pyo3\examples\rustapi_module (master -> origin)
λ pip install .
Processing c:\users\ilya\pyo3\examples\rustapi_module
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: rustapi-module
  Building wheel for rustapi-module (PEP 517) ... error
  ERROR: Complete output from command 'c:\users\ilya\appdata\local\programs\python\python37\python.exe' 'c:\users\ilya\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\Ilya\AppData\Local\Temp\tmp7jhp6429':
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\rustapi_module
  copying rustapi_module\__init__.py -> build\lib\rustapi_module
  running egg_info
  writing rustapi_module.egg-info\PKG-INFO
  writing dependency_links to rustapi_module.egg-info\dependency_links.txt
  writing top-level names to rustapi_module.egg-info\top_level.txt
  reading manifest file 'rustapi_module.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'rustapi_module.egg-info\SOURCES.txt'
  running build_ext
  running build_rust
  error: failed to load source for a dependency on `pyo3`

  Caused by:
    Unable to update C:\Users\Ilya\AppData\Local

  Caused by:
    failed to read `C:\Users\Ilya\AppData\Local\Cargo.toml`

  Caused by:
    The system cannot find the file specified. (os error 2)
  Traceback (most recent call last):
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 141, in build_wheel
      metadata_directory)
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\setuptools\build_meta.py", line 192, in build_wheel
      self.run_setup()
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\setuptools\build_meta.py", line 141, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 112, in <module>
      'sdist': CargoModifiedSdist,
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command

      cmd_obj.run()
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command

      cmd_obj.run()
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command

      cmd_obj.run()
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\setuptools_rust\build_ext.py", line 26, in run
      build_rust.run()
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\setuptools_rust\build.py", line 313, in run
      self.build_extension(ext)
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\setuptools_rust\build.py", line 95, in build_extension
      metadata = json.loads(check_output(metadata_command).decode("utf-8"))
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\subprocess.py", line 389, in check_output
      **kwargs).stdout
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\subprocess.py", line 481, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
  ----------------------------------------
  ERROR: Failed building wheel for rustapi-module
  Running setup.py clean for rustapi-module
Failed to build rustapi-module
ERROR: Could not build wheels for rustapi-module which use PEP 517 and cannot be installed directly
```

**Comment by pganssle** [comment]
@ikamensh Yeah, that's what I'm getting as well. I'm not sure where the bug is there, but that module is mostly for exercising the Rust API, not something end-users are intended to install and use, so for now the best thing to do is to run the tests for the module using `tox`.
