### ISSUE TITLE
examples/rustapi_module doesn't work on windows 10

### ISSUE THREAD

**Issue by ikamensh** [PyO3/pyo3#521]
When reporting a bug, please provide the following information. If this is not a bug report you can just discard this template.

🌍 Environment
Your operating system and version: Windows 10
Your python version: 3.7.1
How did you install python (e.g. apt or pyenv)?: .exe installer, no virtualenv
Your rust version (rustc --version): rustc 1.37.0-nightly (088b98730 2019-07-03)
Are you using the latest pyo3 version? Have you tried using latest master (replace version = "0.x.y" with git = "https://github.com/PyO3/pyo3")? latest (4th July 2019) from github

💥 Reproducing
```
git clone https://github.com/PyO3/pyo3.git
cd pyo3/examples/rustapi_module
pip install -r requirements-dev.txt
pip install .
```

results in an error:
```
C:\Users\Ilya\pyo3\examples\rustapi_module (master -> origin)
λ pip install .
Processing c:\users\ilya\pyo3\examples\rustapi_module
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: rustapi-module
  Building wheel for rustapi-module (PEP 517) ... error
  ERROR: Complete output from command 'c:\users\ilya\appdata\local\programs\python\python37\python.exe' 'c:\users\ilya\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\Ilya\AppData\Local\Temp\tmp7jhp6429':
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\rustapi_module
  copying rustapi_module\__init__.py -> build\lib\rustapi_module
  running egg_info
  writing rustapi_module.egg-info\PKG-INFO
  writing dependency_links to rustapi_module.egg-info\dependency_links.txt
  writing top-level names to rustapi_module.egg-info\top_level.txt
  reading manifest file 'rustapi_module.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'rustapi_module.egg-info\SOURCES.txt'
  running build_ext
  running build_rust
  error: failed to load source for a dependency on `pyo3`

  Caused by:
    Unable to update C:\Users\Ilya\AppData\Local

  Caused by:
    failed to read `C:\Users\Ilya\AppData\Local\Cargo.toml`

  Caused by:
    The system cannot find the file specified. (os error 2)
  Traceback (most recent call last):
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
      main()
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 141, in build_wheel
      metadata_directory)
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\setuptools\build_meta.py", line 192, in build_wheel
      self.run_setup()
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\setuptools\build_meta.py", line 141, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 112, in <module>
      'sdist': CargoModifiedSdist,
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command

      cmd_obj.run()
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command

      cmd_obj.run()
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command

      cmd_obj.run()
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\setuptools_rust\build_ext.py", line 26, in run
      build_rust.run()
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\setuptools_rust\build.py", line 313, in run
      self.build_extension(ext)
    File "C:\Users\Ilya\AppData\Local\Temp\pip-build-env-mnof880p\overlay\Lib\site-packages\setuptools_rust\build.py", line 95, in build_extension
      metadata = json.loads(check_output(metadata_command).decode("utf-8"))
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\subprocess.py", line 389, in check_output
      **kwargs).stdout
    File "c:\users\ilya\appdata\local\programs\python\python37\lib\subprocess.py", line 481, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
  ----------------------------------------
  ERROR: Failed building wheel for rustapi-module
  Running setup.py clean for rustapi-module
Failed to build rustapi-module
ERROR: Could not build wheels for rustapi-module which use PEP 517 and cannot be installed directly

```

**Comment by pganssle** [comment]
This may be a bug in `pip`, actually (though we should probably be testing this in the CI somewhere to catch these early). If you use `pep517.build` to build a wheel for the module, it succeeds in creating a wheel that you can install:

```bash
$ pip install pep517
$ python -m pep517.build -b .
...
$ ls dist
rustapi_module-0.1.0-cp37-cp37m-linux_x86_64.whl
$ pip install dist/rustapi_module-0.1.0-cp37-cp37m-linux_x86_64.whl 
Processing ./dist/rustapi_module-0.1.0-cp37-cp37m-linux_x86_64.whl
Installing collected packages: rustapi-module
Successfully installed rustapi-module-0.1.0
```

Similarly, `tox -e py37` will correctly build and install this project into its virtual environments. Admittedly this is a kind of screwy project, but two other PEP 517 implementations not having a problem with it does lead me to believe that this may be on `pip`.

One possibility is that `pep517` and `tox` may both build source distributions first, then create wheels from the source distributions (I know `tox` does, I am not sure if `pep517.build` does). To work around the requirement that these modules be built against the version of `pyo3` that is in the local directory, we [modify the `Cargo.toml` of the source distribution](https://github.com/PyO3/pyo3/blob/master/examples/rustapi_module/setup.py#L23); without that modification, the installation won't work.

If having these things be directly installable by `pip` is important, we may need to figure out what pathway `bdist_wheel` takes and modify the version of `Cargo.toml` that it uses (preferably without modifying the sdist).

Either way we should document this stuff somewhere, considering this also applies to the `word-count` examples, and all of these modules are in the "examples" directory.

**Comment by konstin** [comment]
AFAIK what pip does for PEP 517 is first to copy the complete project directory to a new temporary directory. In that directory pip calls `bdist_wheel`, and falls back to `setup.py install` if that failed. Unfortunately pip has no documentation about their interpretation of PEP 517 to verify that.

While PEP 517 specifies that "All hooks are run with working directory set to the root of the source tree, [...]", it lacks a definition of what a source tree actually is. (It only says "A source tree is something like a VCS checkout."). The PEP seems to assume though that the source tree is the directory containing the pyproject.toml, which is equal to the root directory of the project in version control. So imho the root problem is PEP 517 missing a definition for "source tree" and not providing a solution for git repositories with multiple projects (I think git repositories with multiple python projects would have the same problem), but pip could circumvent that by either adding an option to build a source distribution before building a wheel or by having an option for building in-place with PEP 517.

> If having these things be directly installable by pip is important, we may need to figure out what pathway bdist_wheel takes and modify the version of Cargo.toml that it uses (preferably without modifying the sdist).

As far as I know `bdist_wheel` is executed in the temporary directory, so it doesn't know the original project directory, and afaik the only option would be using `os.environ["PWD"]`, but I don't know if that is reliable and possible on all platforms.

**Comment by davidhewitt** [comment]
As of `pip >= 20.1` this problem should no longer occur 🚀
