### ISSUE TITLE
Is it possible to specify a local venv path to use at runtime? (python in rust)

### ISSUE THREAD

**Issue by kajogo777** [PyO3/pyo3#723]
It is much cleaner to be able to choose a local venv in runtime rather than rely on packages being globally installed

I am trying to orchestrate python modules being executed using user input data then forwarding results etc..

**Comment by davidhewitt** [comment]
@kajogo777 can you give a more specific example of what you want? E.g. the steps you're trying to do, and what step fails.

**Comment by dralley** [comment]
@davidhewitt I think the problem they are experiencing is that if you try to install the word count example inside of a virtualenv, you get the error:

```
running build_rust
error: failed to read `/home/dalley/Devel/foss-dev/pyo3/examples/.env/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Cargo.toml is obviously in the ```examples/word-count/``` directory, not in ```examples/.env/```, which is the local virtualenv.

**Comment by davidhewitt** [comment]
@dralley can you give me the exact command you're running which fails? (And OS, pyo3, pip versions if relevant)

**Comment by dralley** [comment]
Fedora 32, Python 3.8, pyo3 master, pip 19.3.1

1. Created a virtual environment in ```examples/``` directory and activated it
2. Moved to ```word-count```directory
3. Tried both ```python setup.py install``` and ```pip install -e .```
4. See identical error for both

```
Installing collected packages: word-count
  Running setup.py develop for word-count
    ERROR: Command errored out with exit status 1:
     command: /home/dalley/Devel/foss-dev/pyo3/examples/.env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/dalley/Devel/foss-dev/pyo3/examples/word-count/setup.py'"'"'; __file__='"'"'/home/dalley/Devel/foss-dev/pyo3/examples/word-count/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/dalley/Devel/foss-dev/pyo3/examples/word-count/
    Complete output (45 lines):
    running develop
    running egg_info
    writing word_count.egg-info/PKG-INFO
    writing dependency_links to word_count.egg-info/dependency_links.txt
    writing top-level names to word_count.egg-info/top_level.txt
    reading manifest file 'word_count.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'word_count.egg-info/SOURCES.txt'
    running build_ext
    running build_rust
    error: failed to read `/home/dalley/Devel/foss-dev/pyo3/examples/.env/Cargo.toml`
    
    Caused by:
      No such file or directory (os error 2)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/dalley/Devel/foss-dev/pyo3/examples/word-count/setup.py", line 72, in <module>
        setup(
      File "/tmp/pip-build-env-5pczqmm8/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-5pczqmm8/overlay/lib/python3.8/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/tmp/pip-build-env-5pczqmm8/overlay/lib/python3.8/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-5pczqmm8/overlay/lib/python3.8/site-packages/setuptools_rust/build_ext.py", line 26, in run
        build_rust.run()
      File "/tmp/pip-build-env-5pczqmm8/overlay/lib/python3.8/site-packages/setuptools_rust/build.py", line 313, in run
        self.build_extension(ext)
      File "/tmp/pip-build-env-5pczqmm8/overlay/lib/python3.8/site-packages/setuptools_rust/build.py", line 95, in build_extension
        metadata = json.loads(check_output(metadata_command).decode("utf-8"))
      File "/usr/lib64/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib64/python3.8/subprocess.py", line 512, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/dalley/Devel/foss-dev/pyo3/examples/.env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/dalley/Devel/foss-dev/pyo3/examples/word-count/setup.py'"'"'; __file__='"'"'/home/dalley/Devel/foss-dev/pyo3/examples/word-count/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by dralley** [comment]
It looks like this is reported under setuptools-rust

https://github.com/PyO3/setuptools-rust/issues/56
https://github.com/PyO3/setuptools-rust/issues/46

**Comment by dralley** [comment]
Actually, it might just be an interaction between cargo and virtualenvs that is difficult to avoid:

```
(.env) [dalley@localhost word-count]$ cargo metadata
error: failed to read `/home/dalley/Devel/foss-dev/pyo3/examples/.env/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

```

**Comment by davidhewitt** [comment]
Interestingly, on my WSL system (ubuntu 18.04), I can reproduce the issue you see above if I create a `.env` directory in the examples folder (using `python3.8 -m venv $(pwd)/.env`).

However, if I use a virtualenv ceated by `virtualenvwrapper` (also using `python3.8`), I have no issues. 

Might do some digging another time to figure out what's happening.
